Added test for package
Agent-Hellboy/trace-dkey pull request #4
Opened 2022-10-28 02:01 UTC by aadityasinha-dotcom

fixes #2 
Consider this as my hacktober fest submission and please add `hacktoberfest-accepted` tag also.

2022-10-28 03:20 UTC, Agent-Hellboy commented
@aadityasinha-dotcom Thanks for the PR

Here are some of the pointers

1 change your commit message 
   commit message should be ->  Add test for package 
   please follow this 
   https://cbea.ms/git-commit/

 2 use pytest to write unittest  

 3  Unittest are mostly written considering in mind the edge case 

 4 In python dict keys can be hashable so try to find what is the data structure which is hashable and tries to write the test for that

2022-10-28 03:28 UTC, Agent-Hellboy requested changes

2022-10-28 03:28 UTC, Agent-Hellboy commented on tests/test.py
> +from trace_dkey import trace
use pytest, pytest has fixture, which will be handy to write unit test for these kind of package

2022-10-28 03:28 UTC, Agent-Hellboy commented on tests/test.py
> +def test_trace():
test more scenarios, one of the example could be dict having keys as a tuple

2022-10-28 03:41 UTC, Agent-Hellboy commented
And the most important point is you should focus on increasing the code coverage, sorry I should put these in description of the issue

2022-10-28 03:55 UTC, aadityasinha-dotcom commented
@Agent-Hellboy thanks for the review will make those changes

2022-10-28 17:02 UTC, aadityasinha-dotcom commented
@Agent-Hellboy can you review the changes

2022-10-28 17:11 UTC, Agent-Hellboy requested changes

2022-10-28 17:11 UTC, Agent-Hellboy commented on tests/test.py
> +from trace_dkey import trace
you haven't used pytest yet, look at this to get an idea of `how I have used pytest`
https://github.com/Agent-Hellboy/log_call/blob/main/tests/test_log_call.py

2022-10-28 17:11 UTC, Agent-Hellboy commented on tests/test.py
> +    assert l['a']['b']['c']['d']['e']['f']==('h','i')
I told you to check for a tuple as a key, not a value, this is a lib to track keys inside a dict

2022-10-28 17:12 UTC, Agent-Hellboy commented
> @Agent-Hellboy can you review the changes

you haven't used pytest

2022-10-29 06:00 UTC, aadityasinha-dotcom commented
> > @Agent-Hellboy can you review the changes
> 
> you haven't used pytest

@Agent-Hellboy   Added pytest fixtures can u review that.

2022-10-29 06:14 UTC, aadityasinha-dotcom commented
@Agent-Hellboy can you also add `hacktoberfest` tag in your repository please

2022-10-29 07:17 UTC, Agent-Hellboy commented
>@Agent-Hellboy Added pytest fixtures can u review that?

I don't know what kind of hurry you are in, you haven't tested any of the APIs, please do ask questions if are not able to move further or are not able to understand anything.

If I merge this PR then our code coverage will be 0%

I am coauthoring this PR as the current implementation had made writing unit test difficult, I hope you will understand something from this.

2022-10-29 07:19 UTC, Agent-Hellboy commented
please check, https://github.com/Agent-Hellboy/trace-dkey/pull/6

2022-10-29 07:19 UTC, closed without merging

2022-10-29 17:28 UTC, aadityasinha-dotcom commented
Sorry

2022-10-29 17:43 UTC, aadityasinha-dotcom commented
If u have any task u can assign me I am ready to work on.